name: senior_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  scribble: ^0.9.0
  shared_preferences: ^2.2.2
  image: ^4.0.18
  path_provider: ^2.1.3
  firebase_app_check: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lingua_flow.png